### PR TITLE
Fixed minor typos in the Trin Book

### PR DESCRIPTION
**Pull request by Perelyn-sama**
### What was wrong?
Typos

### How was it fixed?
Corrected them

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [ ] Clean up commit history

### CODE REVIEW

**Comment by njgheorghita** [comment]
Thanks @Perelyn-sama ! Could you just squash your commits into a single commit and then we're good to merge

**Comment by Perelyn-sama** [comment]
Good enough? Kolby's commit before mine just made things complicated

**Comment by njgheorghita** [comment]
Sorry, but not yet. Not quite sure what happened here to get those extra changes. I wouldn't want to include any additional changes in this merge that aren't directly related to the pr and you'll need to rebase against master to resolve the merge conflict.

**Comment by Perelyn-sama** [comment]
Okay, I'll work on it.
I love git :)

**Pull request closed without merging**
