### PR TITLE
chore: Remove our implementation of NodeId

### LINKED ISSUE #869: Deprecate native NodeId implementation
Remove the [native type implementation](https://github.com/ethereum/trin/blob/da85728e5e38916ba8eddf6e5e97201d70d88a91/ethportal-api/src/types/node_id.rs#L29), and replace all usage with the equivalent type from the [discv5 crate](https://github.com/sigp/discv5).

- [ ] Make sure that all of our `portal_*traceRecursiveFindContent` jsonrpc api endpoints correctly ser/de the response
- [ ] Run it against [portal-hive](https://github.com/ethereum/portal-hive)

### PR DESCRIPTION
**Pull request by morph-dev**
### What was wrong?
We have our own implementation of NodeId, which is no longer needed (see #869)

Closes #869.

### CODE REVIEW

**Review by njgheorghita — APPROVED** [review]
:ship: Looks good to me! For some reason, I assumed that there would be a lot more changes as a result of this update, but it seems to me like you've covered everything here. One note, is to just update the pr description to `"closes #869"` so that the issue will be automatically closed once this pr is merged. Thanks!

**Comment by morph-dev** [comment]
I was thinking about that, but decided not to do it because bug also says:

> Run it against [portal-hive](https://github.com/ethereum/portal-hive)

Is that something that should be done as part of this pr before merging (and how?), or something to be done once it's merged (but before closing the bug)?

**Comment by njgheorghita** [comment]
@morph-dev Ahh, good catch. Have you run it against portal-hive locally? I'd recommend doing that before merging this pr. Of course, if we go ahead with the merge, we will soon find out if it passes portal-hive, but I think it's better to confirm that it passes portal-hive locally before merging this through

**Review by KolbyML — APPROVED** [review]
:shipit: :partying_face:

**Review by ogenev — APPROVED** [review]
LGTM :+1:

**Comment by morph-dev** [comment]
Which portal-hive tests should I run? I think I ran all of them, and these are the result:

| Test | Results |
|-|-|
| rpc-compat | all pass |
| portal-mesh | all pass |
| portal-interop | 7 failed 1st run <br> 4 failed 2nd run |
| ts-sim-test | 1 failed |
| get-block-by-hash | 7 failed |
| trin-bridge | 9 failed |

This is similar but slightly worse than results at https://portal-hive.ethdevops.io/.
I don't know if those extra failures are caused by me or not. Any advice?

**Comment by KolbyML** [comment]
Which clients did you run and which tests failed in portal-interop between what clients

**Comment by KolbyML** [comment]
If the test includes ultralight you can ignore it and we are good to merge if it comes up for tests which are trin/fluffy that is concerning

**Comment by morph-dev** [comment]
In second run I used this command:
```bash
./hive --sim portal-interop --client fluffy,ultralight,trin
```

These tests failed:
GOSSIP blocks from A:trin --> B:fluffy
GOSSIP blocks from A:trin --> B:ultralight
GOSSIP blocks from A:ultralight --> B:fluffy
GOSSIP blocks from A:ultralight --> B:trin

**Comment by KolbyML** [comment]
This is good to merge then

**Comment by KolbyML** [comment]
Wait actually nvm I will look into it more

**Comment by KolbyML** [comment]
What is the fail reason given for GOSSIP blocks from A:trin --> B:fluffy?

**Comment by morph-dev** [comment]
```json
    "173": {
      "name": "GOSSIP blocks from A:trin --\u003e B:fluffy",
      "description": "",
      "start": "2023-12-14T16:51:56.389867412+02:00",
      "end": "2023-12-14T16:52:11.282737476+02:00",
      "summaryResult": {
        "pass": false,
        "details": "Client B: [\"Error content for block 17510000 (post-shanghai) block body was absent\", \"Error content for block 17510000 (post-shanghai) receipt was absent\"]"
      },
      "clientInfo": {
        "00343e15": {
          "id": "00343e15",
          "ip": "172.17.0.5",
          "name": "fluffy",
          "instantiatedAt": "2023-12-14T16:51:57.480046961+02:00",
          "logFile": "fluffy/client-00343e15735ccbba69fbeeb4dad3a78139e0d04e06b50603d7a61f54623448c2.log"
        },
        "d1ebef78": {
          "id": "d1ebef78",
          "ip": "172.17.0.4",
          "name": "trin",
          "instantiatedAt": "2023-12-14T16:51:56.87565928+02:00",
          "logFile": "trin/client-d1ebef78a56260c20092203a8e2af0f5857024b0e5064cc6a91f8eae656e15dc.log"
        }
      }
    },
```

**Comment by KolbyML** [comment]
Ok yeah this looks good to merge we are increasing the timeout in the PR I am waiting to merge on Portal-Hive.
This doesn't seem like an interop problem or different tests would have failed with this change.

**Pull request merged**
