### PR TITLE
change web3_ipc_path from String to PathBuf

### PR DESCRIPTION
**Pull request by KolbyML**
### What was wrong?
Fixes todo added in this https://github.com/ethereum/trin/pull/44 PR
### How was it fixed?
Instead of using String/&str I converted the types of Path or PathBuf where it made sense. Basically just using PathBuf instead of using a String

### CODE REVIEW

**Review by ogenev — COMMENTED** [review]
I would change all path function arguments to accept the trait `AsRef<Path>` which will allow `Path`, `PathBuf`, and strings.

**Comment by KolbyML** [comment]
> I would change all path function arguments to accept the trait `AsRef<Path>` which will allow `Path`, `PathBuf`, and strings.

Should we do that though for example 
image
this has to use a Box wouldn't that be unidealistic?

**Comment by ogenev** [comment]
> this has to use a Box wouldn't that be unidealistic?

We use `Box` because the function arguments must be with known size on compile time; in this case, a trait is with unknown size and that's why we wrap it in a Box which is a smart pointer.

We can also use generics, this would look like:

```rust
fn foo<T: AsRef<Path>>(path: T)
```

**Review by ogenev — APPROVED** [review]
Looks good :+1: .

**Pull request merged**
