### PR TITLE
Remove cli, fix windows compilation, move grafana create to TrinConfig, update ``trin-types`` to use clap

### PR DESCRIPTION
**Pull request by KolbyML**
### What was wrong?
fixes https://github.com/ethereum/trin/issues/573 (``trin-cli`` removal as talked about in the meeting 5/11/2023)
fixes Trin so that it can compile to windows
supercedes https://github.com/ethereum/trin/pull/698 (structout to clap conversion for trin-types)
updates/makes a few fixes to the trin book for grafana setup
### How was it fixed?

1. removed json-rpc from ``trin-cli``
2. removed encodekey from ``trin-cli``
3. add cfg and add a few panics to clearly define what is not supported by windows so it can compile
4. remove ``trin-cli``, move Create Grafana dashboard to TrinConfig (as discussed in the meeting 5/11/2023), update ``trin-types`` from structopt to clap
5. update Trin Book

I updated structopt to clap since it was more work to keep structopt then just use clap, there is a WIP PR for it but it has been stalled for 2 weeks now of lack of development

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [x] Add entry to the [release notes](https://github.com/ethereum/trin/blob/master/newsfragments/README.md) (may forgo for trivial changes)
- [x] Clean up commit history

### CODE REVIEW

**Comment by ogenev** [comment]
I would like to see this split into separate PRs. Reading the PR title suggests that this should be at least 3 separate PRs.

We want to do this because it is a lot easier for reviewers to spot any issues when the PR length is shorter and relates only to a single context.

**Comment by KolbyML** [comment]
> I would like to see this split into separate PRs. Reading the PR title suggests that this should be at least 3 separate PRs.
> 
> We want to do this because it is a lot easier for reviewers to spot any issues when the PR length is shorter and when it relates only to a single context.
> 
> Sometimes of course, this is not possible because a single feature requires changes all over the place but in this case I clearly see 3 different contexts: 1. `trin-cli` depreciation/move grafana 2. Fix Windows compilation 3. Update trin-types to use clap.

if moving grafana is seperate from clap grafana won't work till that is in then

**Comment by KolbyML** [comment]
windows requires deprecation of json-rpc.
grafana requires clap for context

**Comment by KolbyML** [comment]
@ogenev @njgheorghita ok I split it into #737 #738 #739 #740 #741 

#741 has to be reviewed/merged after #740 

#737 #738 are the removal of ``json-rpc`` and ``encodekey`` so if we want we can go straight to #741 or review #737 #738 to take burden off #741

**Comment by KolbyML** [comment]
The PR has been split into 5 smaller PR's

**Pull request closed without merging**
