### PR TITLE
Add transaction hashes and uncles to the block that json-rpc returns

### LINKED ISSUE #279: eth_getBlockByHash response should include uncles and txs
To be compliant with the eth json-rpc api spec, the [object returned from `eth_getBlockByHash` request](https://eth.wiki/json-rpc/API#eth_getblockbyhash) should include a list of uncle hashes and transaction hashes. Also, support for the `full_transactions` param would be nice to have.

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

Fix #279 

### To-Do

- [x] Clean up commit history
- [x] Test that txn hashes match expected value
- [x] ~Add uncles~ Hah right, [there are no uncles post-merge](https://ethereum.stackexchange.com/questions/139390/are-uncle-ommer-blocks-still-possible-after-the-merge).
- [x] rebase all the things

### CODE REVIEW

**Comment by carver** [comment]
Ok, ready for review! It's probably easiest to separate reviews out into the linked PRs and then the remaining piece here.

I'll consider a 👍🏻 here as *only* about the part unique to this PR. I will handle any blocking comments on other PRs first, so the comments on this PR can be focused to the unique part of it. Currently:
- [chore: add `From<H256>` for BlockBodyKey](https://github.com/ethereum/trin/pull/963/commits/3de9a87de0b6b447ca0cd23ce09bafb1b2e9728b)
[3de9a87](https://github.com/ethereum/trin/pull/963/commits/3de9a87de0b6b447ca0cd23ce09bafb1b2e9728b)
- [refactor(rpc): fetch & decode any content value](https://github.com/ethereum/trin/pull/963/commits/62269640f9580a9f0bed8f33573e6ea6ee9a8f86)
[6226964](https://github.com/ethereum/trin/pull/963/commits/62269640f9580a9f0bed8f33573e6ea6ee9a8f86)
- [feat(rpc): add txn hashes in eth_getBlockByHash](https://github.com/ethereum/trin/pull/963/commits/5d1a26f1a707a0adb98a2e61d99c39de2121819b)
[5d1a26f](https://github.com/ethereum/trin/pull/963/commits/5d1a26f1a707a0adb98a2e61d99c39de2121819b)

**Comment by ogenev** [comment]
I'm confused, does this PR need review only on two commits: 50e1ce6fcc1f0c34692d645b182367ae8ff9e40a and cd78ef831b000a027f6ecfa3c6504137a83c59ee ?

**Comment by carver** [comment]
> I'm confused, does this PR need review only on two commits: [50e1ce6](https://github.com/ethereum/trin/commit/50e1ce6fcc1f0c34692d645b182367ae8ff9e40a) and [cd78ef8](https://github.com/ethereum/trin/commit/cd78ef831b000a027f6ecfa3c6504137a83c59ee) ?

Nope, the opposite. :) The three commits I listed are the ones that are for this PR review.

**Review by njgheorghita — APPROVED** [review]
Nice! I guess next is to add support for hydrated txs?

**Comment by carver** [comment]
> Nice! I guess next is to add support for hydrated txs?

Yup! I'm working on a local copy now. I'll get my WIP for that up today or tomorrow

**Review by ogenev — APPROVED** [review]
:rocket:

**Pull request merged**
