### PR TITLE
Fixed two issues found in uTP impl

### PR DESCRIPTION
**Pull request by KolbyML**
@KonradStaniec notified me of issues he found during his testing of the interop between fluffy and trin.

Here is a PR of the changes he requested and a few other spots I found the same issues he pointed out.

### CODE REVIEW

**Review by pipermerriam — COMMENTED** [review]
Is there a way to write a test for this?  It is often good practice when addressing a bug to first write a test that demonstrates the failure and then to fix it.  Otherwise, it's not always clear that the issue has actually been resolved correctly.

**Comment by KolbyML** [comment]
@pipermerriam I believe the only way to write tests for this would be to add integration tests. I remember I wanted to write some when I was making the PR, but there was some issue like it would be better to write an integration testing framework first or something.

**Comment by ogenev** [comment]
> @pipermerriam I believe the only way to write tests for this would be to add integration tests. I remember I wanted to write some when I was making the PR, but there was some issue like it would be better to write an integration testing framework first or something.

We have now the test harness (ethportal-peertest), I think we can use it for those kinds of cross-clients integration tests. We still need to decide on the implementation details but the proposition is to have for example cross-client utp test suite which we can run in CicrleCI or localy. What do you think @njgheorghita?

**Comment by njgheorghita** [comment]
It seems like we want two different sets of integration tests, one for trin and one for cross-client. There's a ton of overlap between the two, so it makes sense to build them in the same place. But, i'd recommend keeping the cross-client tests under a separate flag at least during the early stages of development

**Comment by KolbyML** [comment]
@ogenev @njgheorghita to be clear I would want integration tests for Trin so a Trin client would connect to a Trin client. So Nick seemed to pick up on that. For early testing just having an integration testing framework (where we could test Trin to itself to clarify) would be great because once we have the deadlock problem solve issues like that can be avoided, also we could easily test whether things like uTP work properly.

Anyways I think this discussion should probably become an issue and if there are no issues with the PR itself it can be merged.

**Comment by njgheorghita** [comment]
@KolbyML Sorry, I missed this. Yeah, let's get this merged. I added a task for utp-specific tests in #185 so we don't drop that thread

**Pull request merged**
