### PR TITLE
Depend on released trin-types and trin-utils

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

We can't release ethportal-api with a relative dependency.

### How was it fixed?

Switch to depending on the released versions.

### To-Do

- [ ] Clean up commit history

### CODE REVIEW

**Comment by carver** [comment]
So trin-bridge adds both trin-types and ethportal-api as dependencies. That causes a conflict. The most obvious way to fix it is to depend on the released version of trin-types everywhere. (Although that sucks, because it forces releases when changes would normally happen in convenient lockstep.

We can already see an example of that with #697 which could happen atomically before this change, but requires a trin-types release after this change.

I'll try to get the next trin-types release out today.

**Comment by carver** [comment]
I'm actually not certain that we have to do this with trin-utils everywhere, too. So that's something else I want to experiment with.

**Comment by ogenev** [comment]
Can we change only the `ethportal-api` and `trin-bridge` dependencies to the released versions?

**Comment by njgheorghita** [comment]
@carver Seems we can close this post #723 ?

**Pull request closed without merging**
