### PR TITLE
Add params member to JSON-RPC request

### PR DESCRIPTION
**Pull request by ogenev**
Adds support for parsing parameters for the JSON-RPC call.

Fixes https://github.com/ethereum/trin/issues/96

### CODE REVIEW

**Review by njgheorghita — APPROVED** [review]
Looks good! I love the test - but it seems like a test that could benefit from [parameterization](https://docs.rs/rstest/0.11.0/rstest/#creating-parametrized-tests). I'm just bringing it up now since I've run into a couple similar situations on my local branches. From what I can tell, [rstest](https://docs.rs/rstest/0.11.0/rstest/) is probably the best crate to use for various testing utils. Even if it's not necessary for this test, it seems like a crate we'll want to use in other places as the project grows.

**Comment by ogenev** [comment]
> Looks good! I love the test - but it seems like a test that could benefit from [parameterization](https://docs.rs/rstest/0.11.0/rstest/#creating-parametrized-tests). I'm just bringing it up now since I've run into a couple similar situations on my local branches. From what I can tell, [rstest](https://docs.rs/rstest/0.11.0/rstest/) is probably the best crate to use for various testing utils. Even if it's not necessary for this test, it seems like a crate we'll want to use in other places as the project grows.

Let me tell you a secret, I stole this test from one json-rpc crate :smile:  Good to know about `rstest`, I tried it, but in this case, it requires to add more boilerplate code which I think will look confusing.

**Comment by njgheorghita** [comment]
> I tried it, but in this case, it requires to add more boilerplate code which I think will look confusing.

Fair enough, but I have a feeling like we'll need it sooner or later. Also, it's often worthwhile to add some code complexity if it means improved / more granular tests. Obviously there's a limit somewhere. I don't think it's a blocker for merging this, but you might think about leaving a comment that these tests should be expanded at some point

**Comment by ogenev** [comment]
> Fair enough, but I have a feeling like we'll need it sooner or later. Also, it's often worthwhile to add some code complexity if it means improved / more granular tests. Obviously there's a limit somewhere. I don't think it's a blocker for merging this, but you might think about leaving a comment that these tests should be expanded at some point

Probably you are right, updated the test with parametrization.

**Comment by njgheorghita** [comment]
@ogenev Looks great! Thanks for updating those tests. lgtm!

**Pull request merged**
