### PR TITLE
fix(bridge): change rate limiter period calculation

### PR DESCRIPTION
**Pull request by njgheorghita**
### What was wrong?
When the rate limiter was added, it seems to me like this broke our bridge. Locally (running just trin & inside kurtosis), I'm consistently unable to request any data from any provider, latest / backfill mode. 

The culprit appears to be `GovernorMiddleware::with_period(period)`.. it just doesn't appear to be performing as expected. I've updated it to use the `GovernerMiddleware::per_hour()` limit api, which solves the problem locally. 

### How was it fixed?
- changed default el provider to `geth`, since `erigon` is down
- added some debug logs
- removed the rate limiter (aka governer) and the concept of a daily rate limit

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### CODE REVIEW

**Comment by njgheorghita** [comment]
I'm not sure I like this rate limiter. The problem is that the http responses when the limit was exceeded was simply an `""`. This makes it difficult to propagate a useful error to the user informing them that the rate limit is exceeded. But, I'm looking into a way to see if this is possible

**Comment by njgheorghita** [comment]
On another note, this kind of bug should really have been caught in our testing. Though, testing the bridge isn't straightforward in unit tests....

**Comment by KolbyML** [comment]
image
I think the solution is to handle this error in the retry middleware. Which we weren't handling before

**Comment by KolbyML** [comment]
> On another note, this kind of bug should really have been caught in our testing. Though, testing the bridge isn't straightforward in unit tests....
> 
> Adding a kurtosis run to our ci would be very, very nice for catching these types of bugs.

I think "unit testing" the bridge should be done in hive

**Comment by KolbyML** [comment]
I don't think `GovernerMiddleware::per_hour()` would give a desired response it would just make it so the bridge only works for bursts at the start of every hour. Then a consisent stream through the day

**Comment by njgheorghita** [comment]
@KolbyML tbh, I think there's some other issue going on here with the middleware. When I use `GovernorMiddleware::with_period(period)` - it's not that I'm receiving a 429 error. But rather the response from the provider is simply an empty string - eg `Ok("")` is the response. But when I use `GovernorMiddleware::per_hour()` then the expected response is visible.

**Comment by njgheorghita** [comment]
> I think "unit testing" the bridge should be done in hive

Sure, and iirc it will be possible to integrate this into our ci?

**Comment by KolbyML** [comment]
I am going to test this https://github.com/ethereum/trin/pull/1153 on kurtosis right now and see what happens

**Comment by KolbyML** [comment]
> > I think "unit testing" the bridge should be done in hive
> 
> Sure, and iirc it will be possible to integrate this into our ci?

That is what I heard as well in the testing meeting

**Comment by njgheorghita** [comment]
After talking offline, we decided that the rate limiter is not actually very useful for our use case, especially after introducting era1 file support. So we've decided to remove it entirely

**Comment by njgheorghita** [comment]
@KolbyML ready for another :eyes:

**Review by KolbyML — APPROVED** [review]
You forgot to remove the surf_governer library from the cargo.toml

**Pull request merged**
