### PR TITLE
chore: replace eth2_hashing with ethereum_hashing

### PR DESCRIPTION
**Pull request by come-maiz**
This is a necessary step to update ring, which is necessary to build in risc-v.

Part of #1444.

### What was wrong?

trin fails to build in risc-v

### How was it fixed?

It is still not fixed. This is just one step forward.

### To-Do

[//]: # (Stay ahead of things, add list items here!)
- [ ] Clean up commit history and use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

### CODE REVIEW

**Comment by come-maiz** [comment]
Thanks to @haurog and @michaelsproul for fixing the ring dependency in ethereum_hashing:
https://github.com/sigp/ethereum_hashing/pull/8

**Comment by KolbyML** [comment]
@come-maiz CI is going to fail because how how you named your commit, could you amend the commits name following these guidelines https://www.conventionalcommits.org/en/v1.0.0/

**Comment by KolbyML** [comment]
'chore: replace eth2_hashing with ethereum_hashing'

^ something like this would be good

**Comment by come-maiz** [comment]
Yes, done.

**Comment by come-maiz** [comment]
Yes, done ^_^

**Comment by KolbyML** [comment]
> Yes, done ^_^

Thank you for your first contribution

**Pull request merged**
